"""
slang_service.py — Massive Gen-Z / internet slang engine for VaaniSetu.

- 500+ Gen-Z → Plain English terms
- 150+ Plain → Gen-Z terms
- UK / London / roadman, Irish, Scottish, Hinglish, gaming, TikTok slang
- Whole-word matching, case-insensitive, longest-first
- Optional OpenAI polish for unknown phrases
"""

import re
import logging
from services.ai_service import polish_slang_with_ai

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Gen-Z / Internet → Plain English
# ---------------------------------------------------------------------------
GENZ_TO_PLAIN: dict[str, str] = {
    # ── Core Gen-Z ────────────────────────────────────────────────────────
    "no cap":                       "honestly, no lie",
    "cap":                          "a lie",
    "slay":                         "did an amazing job",
    "slayed":                       "did an amazing job",
    "slaying":                      "doing an amazing job",
    "bussin":                       "really good",
    "bussing":                      "really good",
    "bussin bussin":                "absolutely incredible",
    "slaps":                        "is really good",
    "slap":                         "is really good",
    "hits different":               "feels special in a unique way",
    "hit different":                "felt special in a unique way",
    "rizz":                         "natural charm and charisma",
    "rizzed up":                    "charmed someone",
    "rizzler":                      "someone with a lot of charm",
    "unspoken rizz":                "natural charm without saying anything",
    "mid":                          "mediocre or average",
    "lowkey":                       "somewhat, quietly",
    "highkey":                      "openly, definitely",
    "bet":                          "okay, sure, agreed",
    "fr fr":                        "for real, seriously",
    "fr":                           "for real",
    "ngl":                          "not going to lie",
    "istg":                         "I swear to God",
    "tbh":                          "to be honest",
    "iykyk":                        "if you know, you know",
    "idk":                          "I don't know",
    "imo":                          "in my opinion",
    "imho":                         "in my honest opinion",
    "delulu":                       "delusional",
    "sus":                          "suspicious",
    "ate":                          "performed excellently",
    "ate that":                     "did that perfectly",
    "ate and left no crumbs":       "did something perfectly with no flaws",
    "understood the assignment":    "did exactly what was needed, perfectly",
    "main character energy":        "acting with confidence and self-assurance",
    "main character":               "treating life like you are the protagonist",
    "rent free":                    "constantly on someone's mind",
    "living rent free in my head":  "I can't stop thinking about it",
    "touch grass":                  "go outside and get off the internet",
    "glow up":                      "a positive transformation",
    "stan":                         "be a devoted fan of",
    "ghosting":                     "suddenly stopping all communication",
    "ghosted":                      "stopped communicating suddenly",
    "ghost":                        "stop communicating suddenly",
    "flex":                         "show off",
    "salty":                        "bitter or upset",
    "pressed":                      "bothered or upset",
    "based":                        "admirable and authentic",
    "cringe":                       "embarrassing",
    "cringey":                      "embarrassing",
    "iconic":                       "memorable and remarkable",
    "valid":                        "understandable and acceptable",
    "periodt":                      "period, end of discussion",
    "period":                       "end of discussion, that's final",
    "sheesh":                       "wow, that's impressive",
    "goated":                       "the greatest of all time",
    "goat":                         "greatest of all time",
    "yeet":                         "throw something forcefully",
    "finna":                        "going to",
    "lit":                          "exciting and fun",
    "drip":                         "stylish outfit or fashion",
    "snatched":                     "looking great",
    "spill the tea":                "share the gossip",
    "spill":                        "share the gossip",
    "the tea":                      "the gossip",
    "tea":                          "gossip",
    "throwing shade":               "subtly insulting someone",
    "throw shade":                  "subtly insult someone",
    "shade":                        "a subtle insult",
    "clapback":                     "a witty comeback",
    "clap back":                    "give a witty comeback",
    "ok boomer":                    "dismissive of outdated thinking",
    "it's giving":                  "it feels like or suggests",
    "its giving":                   "it feels like or suggests",
    "giving":                       "suggesting or evoking",
    "vibe check":                   "checking someone's mood or energy",
    "vibe":                         "mood or atmosphere",
    "vibes":                        "mood or atmosphere",
    "immaculate vibes":             "perfect energy and atmosphere",
    "simp":                         "someone overly eager to please someone they like",
    "simping":                      "being overly eager to please someone",
    "ship":                         "support a romantic pairing between people",
    "shipping":                     "supporting a romantic pairing",
    "ratio":                        "got more negative responses than support",
    "ratioed":                      "received more negative responses than support",
    "big W":                        "a big win",
    "big L":                        "a big loss",
    "W":                            "a win",
    "L":                            "a loss",
    "bestie":                       "best friend",
    "fam":                          "family or close friends",
    "deadass":                      "seriously, literally",
    "extra":                        "over the top",
    "ick":                          "a sudden feeling of disgust or turn-off",
    "pov":                          "point of view",
    "npc":                          "someone who seems to lack originality",
    "brain rot":                    "mindless low-quality content",
    "brainrot":                     "mindless low-quality content",
    "skibidi":                      "nonsense or absurd internet trend",
    "sigma":                        "independent, self-reliant person",
    "sigma male":                   "an independent, self-reliant man",
    "alpha":                        "dominant or confident person",
    "gyatt":                        "expression of surprise at someone's appearance",
    "fanum tax":                    "jokingly taking a portion of someone's food",
    "looksmaxxing":                 "trying to improve one's appearance",
    "mewing":                       "a jawline exercise trend",
    "core":                         "aesthetic style",
    "cottagecore":                  "a cozy rural aesthetic",
    "clean girl aesthetic":         "a minimal, natural beauty look",
    "soft launch":                  "subtly revealing a new relationship",
    "hard launch":                  "officially announcing a relationship",
    "situationship":                "an undefined romantic relationship",
    "beige flag":                   "a mildly concerning or quirky trait",
    "red flag":                     "a warning sign in a person",
    "green flag":                   "a positive sign in a person",
    "cheugy":                       "outdated or trying too hard",
    "slay queen":                   "you did amazing",
    "say less":                     "I understand, no need to explain more",
    "on god":                       "I swear it's true",
    "ong":                          "on God, I swear",
    "bop":                          "a catchy song",
    "fire":                         "excellent",
    "go off":                       "express yourself freely",
    "snack":                        "an attractive person",
    "zesty":                        "flamboyant or energetic",
    "unalive":                      "a euphemism for dying or killing",
    "sleeping on":                  "not appreciating something enough",
    "caught in 4k":                 "caught with clear evidence",
    "cooked":                       "done for, in trouble, or ruined",
    "you're cooked":                "you are in trouble or out of options",
    "im cooked":                    "I am in trouble",
    "glazing":                      "excessive praise or flattery",
    "glaze":                        "overpraise someone",
    "aura":                         "the distinct vibe or presence someone gives off",
    "negative aura":                "bad vibe or off-putting energy",
    "positive aura":                "good vibe or appealing energy",
    "crash out":                    "lose control emotionally",
    "locked in":                    "fully focused",
    "ohio":                         "used jokingly to mean weird or cursed",
    "only in ohio":                 "used jokingly for bizarre situations",
    "understood":                   "got it, I understand",
    "no thoughts head empty":       "not thinking about anything",
    "sending me":                   "making me laugh uncontrollably",
    "i'm dead":                     "I'm laughing so hard",
    "i'm deceased":                 "I'm laughing so hard",
    "crying rn":                    "laughing so hard right now",
    "not me":                       "I can't believe I",
    "the way":                      "I can't believe how",
    "lowkey obsessed":              "quietly very interested in",
    "highkey obsessed":             "openly very interested in",
    "understood the vibe":          "got the mood perfectly",
    "ate the look":                 "wore the outfit perfectly",
    "serve":                        "look amazing or perform excellently",
    "serving looks":                "looking amazing",
    "mother":                       "an iconic, admired person",
    "understood the moment":        "perfectly captured the situation",
    "pop off":                      "do something impressive",
    "popped off":                   "did something impressive",
    "understood the energy":        "matched the mood perfectly",
    "understood the assignment fr": "did exactly what was needed, for real",
    "rent free in my head":         "I can't stop thinking about it",
    "understood the fit":           "wore the outfit perfectly",
    "understood the look":          "nailed the appearance",
    "understood the task":          "did exactly what was needed",
    "understood the moment fr":     "perfectly captured the situation, for real",
    # ── Abbreviations ─────────────────────────────────────────────────────
    "lol":   "laughing out loud",
    "lmao":  "laughing my head off",
    "lmfao": "laughing my head off (stronger)",
    "omg":   "oh my God",
    "omfg":  "oh my God (stronger)",
    "wtf":   "what the heck",
    "wth":   "what the heck",
    "smh":   "shaking my head in disbelief",
    "ikr":   "I know, right",
    "imo":   "in my opinion",
    "imho":  "in my honest opinion",
    "irl":   "in real life",
    "afk":   "away from keyboard",
    "brb":   "be right back",
    "gtg":   "got to go",
    "ttyl":  "talk to you later",
    "hmu":   "hit me up, contact me",
    "dm":    "direct message",
    "fomo":  "fear of missing out",
    "jomo":  "joy of missing out",
    "yolo":  "you only live once",
    "tbt":   "throwback Thursday",
    "ootd":  "outfit of the day",
    "grwm":  "get ready with me",
    "asmr":  "relaxing audio content",
    "ngl":   "not going to lie",
    "tbh":   "to be honest",
    "imo":   "in my opinion",
    "fwiw":  "for what it's worth",
    "iirc":  "if I remember correctly",
    "afaik": "as far as I know",
    "eli5":  "explain it simply",
    "tldr":  "too long, didn't read — here's the summary",
    "til":   "today I learned",
    "ama":   "ask me anything",
    "idk":   "I don't know",
    "idgaf": "I don't care at all",
    "idrc":  "I don't really care",
    "nvm":   "never mind",
    "rn":    "right now",
    "atm":   "at the moment",
    "imo":   "in my opinion",
    "tbf":   "to be fair",
    "nbd":   "no big deal",
    "imo":   "in my opinion",
    # ── Gaming slang ──────────────────────────────────────────────────────
    "gg":           "good game",
    "gg ez":        "good game, that was easy",
    "noob":         "a beginner or unskilled player",
    "newbie":       "a beginner",
    "op":           "overpowered",
    "nerf":         "weaken something",
    "buff":         "strengthen something",
    "meta":         "the most effective strategy currently",
    "grind":        "work hard repeatedly",
    "grinding":     "working hard repeatedly",
    "carry":        "lead the team to victory",
    "carried":      "was led to victory by someone else",
    "clutch":       "performed well under pressure",
    "clutched":     "succeeded under pressure",
    "rekt":         "completely defeated",
    "pwned":        "completely defeated",
    "respawn":      "come back after failing",
    "speedrun":     "complete something as fast as possible",
    "speedrunning": "completing something as fast as possible",
    "npc behavior": "acting without original thought",
    "final boss":   "the ultimate challenge",
    "side quest":   "an unplanned detour or task",
    "loot":         "rewards or valuable items",
    "toxic":        "unpleasant or harmful behaviour",
    "throwing":     "deliberately losing or making mistakes",
    "throw":        "deliberately lose or make mistakes",
    "afk":          "away from keyboard, not paying attention",
    "lag":          "slow response or delay",
    "lagging":      "responding slowly",
    # ── Anime / fandom slang ──────────────────────────────────────────────
    "waifu":        "a fictional character someone is very fond of",
    "husbando":     "a male fictional character someone is very fond of",
    "isekai":       "a story where someone is transported to another world",
    "weeb":         "someone very into Japanese anime and culture",
    "otaku":        "someone deeply into anime and manga",
    "senpai":       "an older or more experienced person one admires",
    "kawaii":       "cute",
    "sugoi":        "amazing or incredible",
    "nani":         "what",
    "ara ara":      "an expression of mild surprise or amusement",
    "irl":          "in real life",
    "canon":        "officially part of the story",
    "headcanon":    "a personal interpretation of a story",
    "otp":          "one true pairing, favourite couple",
    "fanfic":       "fan-written fiction",
    "fanart":       "fan-created artwork",
    "crackship":    "an unlikely romantic pairing",
    # ── Hinglish / Indian internet slang ──────────────────────────────────
    "yaar":         "friend",
    "bhai":         "brother or close friend",
    "bro":          "close friend",
    "dost":         "friend",
    "scene kya hai":"what's going on",
    "kya scene hai":"what's the situation",
    "bindaas":      "carefree and cool",
    "jugaad":       "a clever improvised solution",
    "timepass":     "something done to pass time",
    "bakchodi":     "nonsense or foolish talk",
    "bakchod":      "someone who talks nonsense",
    "chapri":       "someone who acts cheap or tries too hard",
    "ilaaj":        "treatment or solution",
    "lafda":        "trouble or a fight",
    "jhol":         "something shady or suspicious",
    "mast":         "great or awesome",
    "ekdum mast":   "absolutely great",
    "solid":        "really good",
    "pataka":       "an attractive person",
    "dhamaka":      "a big exciting event",
    "jugnu":        "a clever or bright person",
    "sahi hai":     "that's right or that's good",
    "bilkul sahi":  "absolutely correct",
    "OP":           "overpowered or extremely good",
    "OP hai":       "this is overpowered or extremely good",
    "full on":      "completely or totally",
    "chill maar":   "relax",
    "tension mat le":"don't worry",
    "khatam tata bye bye": "it's over, goodbye",
    "bhai kya kar raha hai": "what are you doing, man",
    "yaar sun":     "hey friend, listen",
    "ek number":    "first class, excellent",
    "fattu":        "a coward",
    "darpok":       "a coward",
    "ghanta":       "not at all, no way",
    "ullu":         "a fool",
    "pagal":        "crazy",
    "dimag mat kha":"stop bothering me",
    "kya baat hai": "wow, that's impressive",
    "maza aa gaya": "that was fun",
    "bore ho gaya": "I got bored",
    "thoda chill":  "relax a little",
    "zyada mat kar":"don't overdo it",
    "seedha baat":  "speak directly",
    "jugaad lagao": "find a clever workaround",
    # ── UK / Australian slang ─────────────────────────────────────────────
    "innit":        "isn't it, right",
    "bruv":         "brother, close friend",
    "bloke":        "a man",
    "mate":         "friend",
    "cheeky":       "slightly rude but in a fun way",
    "gutted":       "very disappointed",
    "chuffed":      "very pleased",
    "dodgy":        "suspicious or unreliable",
    "proper":       "very or genuinely",
    "bare":         "a lot of",
    "mandem":       "a group of friends",
    "peng":         "attractive or very good",
    "peak":         "unfortunate or bad",
    "wagwan":       "what's going on",
    "roadman":      "someone from the streets",
    "sket":         "a disrespectful term for someone",
    "wasteman":     "a useless or worthless person",
    "link up":      "meet up",
    "link":         "meet up",
    "clock it":     "agreed, that's true",
    "clock that":   "agreed, that's exactly right",
    "clock this":   "agreed, this is it",
    "clocked it":   "called it out or spotted the truth",
    "clocked that": "called that out or noticed the truth",
    "clocked":      "noticed, called out, or saw through something",
    "clocking":     "calling something out or reading the situation",
    "get clocked":  "get called out or exposed",
    "dead":         "boring or not funny",
    "dead ting":    "a boring person",
    "allow it":     "forget it, let it go",
    "calm":         "okay, fine",
    "sick":         "cool or impressive",
    "wicked":       "cool or impressive",
    "legend":       "an amazing person",
    "banter":       "playful teasing",
    "taking the piss": "joking or mocking",
    "sorted":       "arranged or fixed",
    "cheers":       "thank you",
    "ta":           "thank you",
    "reckon":       "think or believe",
    "arvo":         "afternoon",
    "arvo tea":     "afternoon tea",
    "servo":        "petrol station",
    "brekkie":      "breakfast",
    "barbie":       "barbecue",
    "no worries":   "it's fine, don't worry",
    "she'll be right": "everything will be fine",
    "fair dinkum":  "genuine or truly",
    "heaps":        "a lot",
    "ripper":       "excellent",
    "strewth":      "an expression of surprise",
    # ── More Gen-Z / TikTok (2024–2026) ─────────────────────────────────
    "bruh":                         "bro, seriously",
    "broski":                       "bro, friend",
    "no shot":                      "no way, absolutely not",
    "no shot bro":                  "no way, absolutely not",
    "down bad":                     "desperate or obsessed over someone",
    "down horrendous":              "extremely desperate or obsessed",
    "down catastrophic":            "beyond desperate, completely obsessed",
    "side eye":                     "a disapproving or skeptical look",
    "demure":                       "modest and reserved in a refined way",
    "very demure very mindful":     "modest, careful, and self-aware",
    "pick me":                      "someone who seeks attention by putting others down",
    "pick me girl":                 "a girl who seeks male approval by acting different",
    "pick me boy":                  "a guy who seeks attention by acting humble or different",
    "girl math":                    "humorous logic used to justify spending or decisions",
    "boy math":                     "humorous logic used to justify silly male behaviour",
    "girl dinner":                  "a casual snack plate eaten as a meal",
    "dupe":                         "an affordable alternative to an expensive product",
    "moots":                        "mutual followers online",
    "oomf":                         "one of my followers or friends online",
    "finsta":                       "a private secondary Instagram account",
    "soft block":                   "unfollow someone without blocking them",
    "hard block":                   "completely block someone online",
    "parasocial":                   "a one-sided emotional connection to someone online",
    "understood the lore":          "got the backstory and references",
    "understood the reference":     "got the joke or cultural reference",
    "mother is mothering":          "an iconic person is doing what they do best",
    "material gworl":               "someone fabulous who knows their worth",
    "delulu is the solulu":         "being delusional is the only solution",
    "gaslight gatekeep girlboss":   "toxic behaviour disguised as empowerment",
    "negative rizz":                "the ability to repel people socially",
    "rizz god":                     "someone with exceptional charm",
    "rizzless":                     "having no charm at all",
    "its the ___ for me":           "that specific detail is what stands out",
    "big back":                     "having a large appetite (often joking)",
    "no bones day":                 "a day when you need rest and can't push yourself",
    "slay king":                    "you did amazing, king",
    "slay mama":                    "you did amazing",
    "yass":                         "yes, enthusiastically",
    "yas queen":                    "yes, you did amazing",
    "valid af":                     "completely understandable and acceptable",
    "sus af":                       "very suspicious",
    "based af":                     "very admirable and authentic",
    "mid af":                       "very mediocre",
    "caught lacking":               "caught unprepared or without a comeback",
    "caught in 4k hd":              "caught with undeniable clear evidence",
    "its giving main character":    "it feels like someone thinks they are the protagonist",
    "roman empire":                 "something you think about constantly (TikTok trend)",
    "understood the fit":           "nailed the outfit perfectly",
    "quiet luxury":                 "understated, expensive-looking style",
    "old money aesthetic":          "a classy, wealthy-looking style",
    "mob wife aesthetic":           "bold, glamorous, powerful fashion style",
    "corecore":                     "a chaotic, emotional video editing aesthetic",
    "understood the energy":        "matched the mood perfectly",
    "its so over":                  "the situation is hopeless or finished",
    "we're so back":                 "things are good again after a setback",
    "we are so back":               "things are good again after a setback",
    "its so joever":                "it's completely over (internet joke)",
    "joever":                       "completely finished, it's over",
    "chat is this real":            "is this actually happening",
    "chat":                         "audience or viewers (streaming term)",
    "ratio plus l":                 "got overwhelmingly negative responses",
    "didn't ask":                   "your opinion wasn't requested",
    "didn't ask plus ratio":        "nobody asked and you got negative responses",
    "touch some grass":             "go outside and get off the internet",
    "be so for real":               "be serious right now",
    "be fr":                        "be for real, be serious",
    "real asf":                     "very genuine and authentic",
    "lowkey fire":                  "secretly or quietly excellent",
    "highkey fire":                 "openly and obviously excellent",
    "slay diva":                    "you did amazing",
    "understood the lore fr":       "got the backstory, for real",
    "understood the reference fr":  "got the reference, for real",
    "its giving ick":               "it gives me a feeling of disgust",
    "the ick":                      "a sudden turn-off or feeling of disgust",
    "ick factor":                   "something that causes disgust or turn-off",
    "ick list":                     "a list of things that turn you off",
    "understood the assignment ate": "did perfectly and then some",
    "ate and left no crumbs fr":    "did something perfectly, for real",
    "slay period":                  "you did amazing, end of discussion",
    "period slay":                  "you did amazing, end of discussion",
    "understood the assignment period": "did perfectly, end of discussion",
    # ── More abbreviations / text speak ───────────────────────────────────
    "wdym":         "what do you mean",
    "wym":          "what you mean",
    "wsg":          "what's good, what's up",
    "wsp":          "what's up",
    "sup":          "what's up",
    "stfu":         "shut up (rude)",
    "stg":          "I swear to God",
    "icl":          "I can't lie",
    "ngl icl":      "not gonna lie, I can't lie",
    "tbh icl":      "to be honest, I can't lie",
    "bc":           "because",
    "bcuz":         "because",
    "cuz":          "because",
    "ur":           "your or you're",
    "u":            "you",
    "r":            "are",
    "pls":          "please",
    "plz":          "please",
    "thx":          "thanks",
    "ty":           "thank you",
    "np":           "no problem",
    "yw":           "you're welcome",
    "jk":           "just kidding",
    "jkjk":         "just kidding, just kidding",
    "hbu":          "how about you",
    "wbu":          "what about you",
    "hbu tho":      "how about you though",
    "imo tbh":      "in my opinion, to be honest",
    "fyi":          "for your information",
    "asap":         "as soon as possible",
    "bff":          "best friends forever",
    "bffr":         "be for real (emphatic)",
    "bffr rn":      "be for real right now",
    "istg fr":      "I swear to God, for real",
    "ong fr":       "on God, for real",
    "ngl fr":       "not gonna lie, for real",
    "lowk":         "lowkey",
    "highk":        "highkey",
    "prolly":       "probably",
    "def":          "definitely",
    "obvi":         "obviously",
    "obvs":         "obviously",
    "totes":        "totally",
    "v":            "very",
    "bc im":        "because I'm",
    "rn tho":       "right now though",
    "atm rn":       "at the moment right now",
    "lmaoo":        "laughing my head off (extended)",
    "lmaooo":       "laughing extremely hard",
    "rofl":         "rolling on the floor laughing",
    "roflmao":      "rolling on the floor laughing my head off",
    "pov you":      "imagine you are in this situation",
    "pov me":       "imagine I am in this situation",
    "pov them":     "imagine they are in this situation",
    "omw":          "on my way",
    "omw rn":       "on my way right now",
    "wyd":          "what are you doing",
    "wyd rn":       "what are you doing right now",
    "wya":          "where are you at",
    "wya rn":       "where are you at right now",
    "hyd":          "how are you doing",
    "hru":          "how are you",
    "hr u":         "how are you",
    "u good":       "are you good",
    "u ok":         "are you okay",
    "u alright":    "are you alright",
    "lmk":          "let me know",
    "lmki":         "let me know if",
    "plz lmk":      "please let me know",
    "dw":           "don't worry",
    "dw abt it":    "don't worry about it",
    "mb":           "my bad",
    "myb":          "my bad",
    "sry":          "sorry",
    "srry":         "sorry",
    "sry bro":      "sorry, bro",
    "ig":           "I guess",
    "idc":          "I don't care",
    "idt":          "I don't think",
    "idts":         "I don't think so",
    "ion":          "I don't",
    "ion even":     "I don't even",
    "ion know":     "I don't know",
    "otp":          "on the phone",
    "icydk":        "in case you didn't know",
    "icymi":        "in case you missed it",
    "tmi":          "too much information",
    "ofc":          "of course",
    "ofc not":      "of course not",
    "tbqh":         "to be quite honest",
    "ymmv":         "your mileage may vary",
    "iow":          "in other words",
    "otoh":         "on the other hand",
    "ily":          "I love you",
    "ilu":          "I love you",
    "ily2":         "I love you too",
    "ilysm":        "I love you so much",
    "luv u":        "love you",
    "luv ya":       "love you",
    "tyvm":         "thank you very much",
    "tyty":         "thank you, thank you",
    "tysm":         "thank you so much",
    "thx tho":      "thanks though",
    "ty tho":       "thank you though",
    "np tho":       "no problem though",
    "cya":          "see you",
    "cu":           "see you",
    "cul":          "see you later",
    "cul8r":        "see you later",
    "l8r":          "later",
    "ttys":         "talk to you soon",
    "ttfn":         "ta-ta for now",
    "bbs":          "be back soon",
    "bbl":          "be back later",
    "g2g":          "got to go",
    "gn":           "good night",
    "gnight":       "good night",
    "gm":           "good morning",
    "g morning":    "good morning",
    "gl":           "good luck",
    "hf":           "have fun",
    "hbd":          "happy birthday",
    "hb":           "happy birthday",
    "nm":           "nothing much",
    "nmu":          "not much, you?",
    "w/e":          "whatever",
    "whatevs":      "whatever",
    "b4":           "before",
    "abt":          "about",
    "tho":          "though",
    "tho fr":       "though, for real",
    "thru":         "through",
    "w/":           "with",
    "w/o":          "without",
    "srsly":        "seriously",
    "srsly tho":    "seriously though",
    "kk":           "okay",
    "okok":         "okay, okay",
    "nah":          "no",
    "nah fr":       "no, for real",
    "yh":           "yeah",
    "ye":           "yeah",
    "ya":           "yeah",
    "yup":          "yes",
    "yep":          "yes",
    "mhm":          "yes, I understand",
    "mmhm":         "yes, uh-huh",
    "nuh uh":       "no, uh-uh",
    "prob":         "probably",
    "probs":        "probably",
    "defo":         "definitely",
    "deffo":        "definitely",
    "eta":          "estimated time of arrival",
    "psa":          "public service announcement",
    "cmv":          "change my view",
    "nta":          "not the asshole",
    "yta":          "you're the asshole",
    "aita":         "am I the asshole",
    "dni":          "do not interact",
    "dnf":          "do not follow",
    "nsfw":         "not safe for work",
    "sfw":          "safe for work",
    "sfyl":         "sorry for your loss",
    "rip":          "rest in peace, that's unfortunate",
    "f in chat":    "pay respects",
    "lolol":        "laughing out loud (extended)",
    "lolz":         "laughing",
    "meh":          "indifferent, unimpressed",
    "frfr":         "for real, for real",
    "ikr fr":       "I know, right, for real",
    "smh ikr":      "shaking my head, I know right",
    "nvm tho":      "never mind though",
    "nvm fr":       "never mind, for real",
    "tbh ngl":      "to be honest, not gonna lie",
    "ngl tbh":      "not gonna lie, to be honest",
    "imo ngl":      "in my opinion, not gonna lie",
    "idk tbh":      "I don't know, to be honest",
    "idk ngl":      "I don't know, not gonna lie",
    "idk fr":       "I don't know, for real",
    "idc fr":       "I don't care, for real",
    "istg ngl":     "I swear to God, not gonna lie",
    "wyt":          "what you think",
    "wywt":         "what you want to talk about",
    "msg me":       "message me",
    "dm me":        "direct message me",
    "pm me":        "private message me",
    "n1":           "nice one",
    "u bet":        "you bet",
    "im weak":      "I'm laughing so hard",
    "im dead fr":   "I'm laughing so hard, for real",
    "same fr":      "same, for real",
    "same tbh":     "same, to be honest",
    "same ngl":     "same, not gonna lie",
    "same lol":     "same, laughing out loud",
    "lowkey tho":   "somewhat though",
    "highkey tho":  "definitely though",
    "ngl tho":      "not gonna lie though",
    "tbh tho":      "to be honest though",
    "fr tho":       "for real though",
    "no cap fr":    "honestly, for real",
    "cap fr":       "that's a lie, for real",
    "bet fr":       "okay sure, for real",
    "say less fr":  "I understand, for real",
    "tl dr":        "too long, didn't read",
    "tl;dr":        "too long, didn't read",
    "imao":         "laughing my head off (typo of lmao)",
    "uwu":          "cute, affectionate expression",
    "owo":          "cute, surprised expression",
    "xd":           "laughing face",
    "qq":           "crying, sad",
    "brb ttyl":     "be right back, talk to you later",
    "gtg ttyl":     "got to go, talk to you later",
    "ru ok":        "are you okay",
    "r u ok":       "are you okay",
    "r u":          "are you",
    "u r":          "you are",
    "u r welcome":  "you are welcome",
    "bc of":        "because of",
    "bcuz of":      "because of",
    "cuz of":       "because of",
    "kinda":        "kind of",
    "sorta":        "sort of",
    "gonna":        "going to",
    "wanna":        "want to",
    "gotta":        "got to",
    "lemme":        "let me",
    "gimme":        "give me",
    "tryna":        "trying to",
    "bouta":        "about to",
    "finna go":     "going to go",
    "ima":          "I'm going to",
    "imma":         "I'm going to",
    "ion wanna":    "I don't want to",
    "ion like":     "I don't like",
    "didnt":        "didn't",
    "doesnt":       "doesn't",
    "dont":         "don't",
    "cant":         "can't",
    "wont":         "won't",
    "isnt":         "isn't",
    "wasnt":        "wasn't",
    "werent":       "weren't",
    "wouldnt":      "wouldn't",
    "couldnt":      "couldn't",
    "shouldnt":     "shouldn't",
    "havent":       "haven't",
    "hasnt":        "hasn't",
    "hadnt":        "hadn't",
    "aint":         "isn't or aren't",
    "yall":         "you all",
    "ya'll":        "you all",
    "dunno":        "don't know",
    "coulda":       "could have",
    "woulda":       "would have",
    "shoulda":      "should have",
    "musta":        "must have",
    "kinda sus":    "kind of suspicious",
    "lowkey sus":   "somewhat suspicious",
    "highkey sus":  "very suspicious",
    # ── More UK / London / Roadman slang ──────────────────────────────────
    "safe":             "okay, cool, agreed",
    "safe fam":         "alright, friends",
    "safe bro":         "alright, bro",
    "safe mate":        "alright, mate",
    "ting":             "an attractive person or thing",
    "peng ting":        "a very attractive person",
    "buff ting":        "a very attractive person",
    "leng":             "very attractive",
    "leng ting":        "a very attractive person",
    "leng man":         "a very attractive man",
    "leng still":       "still very attractive",
    "peng still":       "still very attractive",
    "peng though":      "very attractive though",
    "pengest":          "the most attractive",
    "butters":          "ugly or unattractive",
    "hench":            "muscular and strong-looking",
    "dench":            "well-built, tough, or excellent",
    "nang":             "excellent or very cool",
    "mint":             "great or excellent",
    "minted":           "very wealthy",
    "blinding":         "excellent, brilliant",
    "cracking":         "excellent, very good",
    "knackered":        "extremely tired",
    "gassed":           "excited, hyped up, or full of yourself",
    "gassed up":        "excited or hyped up",
    "gassed bruv":      "excited or hyped up, bro",
    "jarring":          "awkward, uncomfortable, or annoying",
    "bare jokes":       "very funny or surprising",
    "jokes":            "funny, surprising, or unbelievable",
    "mad ting":         "a crazy or impressive thing",
    "mad still":        "still crazy or impressive",
    "mad one":          "a crazy or wild person or situation",
    "long ting":        "something annoying that takes too long",
    "long":             "annoying, boring, or taking too long",
    "peak ting":        "an unfortunate situation",
    "bare peak":        "very unfortunate",
    "peak still":       "still very unfortunate",
    "peak innit":       "very unfortunate, right",
    "move mad":         "acting crazy or out of control",
    "movin mad":        "acting crazy or out of control",
    "moving mad":       "acting crazy or out of control",
    "bait":             "obvious or suspicious",
    "bait out":         "expose or reveal someone",
    "baiting":          "being obvious or trying to provoke",
    "neek":             "a nerd or uncool person",
    "melt":             "an idiot or foolish person",
    "muppet":           "an idiot or foolish person",
    "div":              "a foolish person (divvy)",
    "wastey":           "a useless person",
    "trim":             "an attractive person",
    "buff":             "attractive or muscular",
    "creps":            "trainers or sneakers",
    "ends":             "your neighbourhood or area",
    "endz":             "your neighbourhood or area",
    "ends man":         "someone from the neighbourhood",
    "ends ting":        "a neighbourhood thing",
    "opps":             "enemies or rivals",
    "opp block":        "enemy territory or rival area",
    "mandem ting":      "a friends-group thing",
    "fam ting":         "a family or close-friends thing",
    "bare mans":        "a lot of people",
    "man's":            "I am, or a person is",
    "gwarn":            "go on, continue",
    "wag1":             "what's going on",
    "ygm":              "you get me",
    "you get me":       "do you understand me",
    "get me":           "do you understand",
    "swear down":       "I swear, honestly",
    "on my mums":       "I swear on my mother",
    "on my life fam":   "I swear on my life, family",
    "allow dat":        "forget it, leave it",
    "swear on my mum":  "I swear on my mother",
    "par":              "insult or embarrass someone",
    "parred":           "insulted or embarrassed someone",
    "get parred":       "get insulted or humiliated",
    "parred off":       "got insulted or rejected",
    "skint":            "broke, no money",
    "brassic":          "completely broke",
    "quids in":         "in profit or doing well financially",
    "quid":             "pounds (money)",
    "sorted mate":      "all arranged, mate",
    "cheeky nandos":    "a cheeky treat (internet meme)",
    "taking the mickey": "joking or mocking someone",
    "miffed":           "annoyed or irritated",
    "naff":             "uncool or poor quality",
    "sarnie":           "sandwich",
    "cuppa":            "a cup of tea",
    "arsey":            "bad-tempered or irritable",
    "bollocks":         "nonsense or rubbish",
    "bloody hell":      "an expression of surprise or frustration",
    "easy peasy":       "very easy",
    "bob's your uncle": "and there you have it, done",
    "chav":             "a stereotype of working-class youth (often insulting)",
    "roadman ting":     "street culture thing",
    "touch road":       "go outside, hit the streets",
    "sound":            "a good, decent person",
    "sound mate":       "good person, mate",
    "sound geezer":     "a good, decent guy",
    "geezer":           "a man or guy",
    "bird":             "a woman (informal, can be rude)",
    "fit":              "attractive",
    "fit still":        "still attractive",
    "peng bro":         "very good, bro",
    "wagwan fam":       "what's going on, family",
    "wagwan my g":      "what's going on, my guy",
    "innit bruv":       "isn't it, bro",
    "bruvva":           "brother, close friend",
    "famalam":          "family or close friends",
    "mandem on ends":   "friends in the neighbourhood",
    "long day":         "a tiring or annoying day",
    "peak times":       "unfortunate situation",
    "dead chat":        "boring conversation or audience",
    "dry":              "boring or unfunny",
    "dry ting":         "a boring person or thing",
    "wet":              "weak or uncool (UK)",
    "moist":            "weak or uncool (UK insult)",
    "dry joke":         "an unfunny joke",
    "banter still":     "still playful teasing",
    "sick still":       "still cool or impressive",
    "wicked still":     "still cool or impressive",
    "legend still":     "still an amazing person",
    "chuffed to bits":  "very pleased and happy",
    "gutted innit":     "very disappointed, right",
    "dodgy still":      "still suspicious",
    "cheeky still":     "still playfully rude",
    "reckon so":        "I think so",
    "reckon not":       "I don't think so",
    # ── Irish / Scottish / regional UK ────────────────────────────────────
    "craic":            "fun, gossip, or good times",
    "grand":            "fine, okay, good",
    "deadly":           "excellent (Irish)",
    "sound out":        "a sound person (Irish/UK)",
    "wee":              "small or little (Scottish/N Irish)",
    "wee bit":          "a little bit",
    "dinnae":           "don't (Scottish)",
    "ken":              "know (Scottish)",
    "bonnie":           "beautiful or pretty (Scottish)",
    "aye":              "yes (Scottish/N English)",
    "naw":              "no (Scottish)",
    "pure":             "very or completely (Scottish)",
    "pure buzzing":     "very excited (Scottish)",
    "baltic":           "freezing cold (UK)",
    "minging":          "disgusting or ugly (UK)",
    "rank":             "disgusting (UK)",
    "lush":             "lovely or attractive (Welsh/UK)",
    "tidy":             "attractive or good (Welsh)",
    "champion":         "excellent (Welsh/UK)",
    "now in a minute":  "soon (Welsh English)",
    "tamping":          "furious (Welsh)",
    "hark at":          "listen to (Northern)",
    "ey up":            "hello (Northern)",
    "alright pet":      "hello, love (Northern)",
    "love mate":        "term of endearment (UK)",
    "alright love":     "hello, love (UK)",
    "pet":              "term of endearment (Northern)",
    "duck":             "term of endearment (Midlands)",
    "me duck":          "my dear (Midlands)",
    "ar kid":           "my friend (Liverpool)",
    "sound as a pound": "very good (Northern)",
    "made up":          "very pleased (Northern)",
    "gobsmacked":       "utterly shocked",
    "chuffed as nuts":  "extremely pleased",
    # ── More Hinglish / desi internet ─────────────────────────────────────
    "arre yaar":        "oh come on, friend",
    "accha":            "okay, good",
    "theek hai":        "it's fine, okay",
    "bas kar":          "stop it, enough",
    "kya re":           "what's up",
    "aur bata":         "tell me more",
    "sahi mein":        "really, for real",
    "pakka":            "definitely, for sure",
    "jugaadu":          "someone who finds clever workarounds",
    "time pass":        "something to kill time",
    "desi":             "South Asian or culturally Indian",
    "desi vibe":        "South Asian cultural feel",
    "filmy":            "dramatic like a Bollywood movie",
    "filmy moment":     "a dramatic Bollywood-style moment",
    "jai ho":           "expression of triumph or celebration",
    "shabaash":         "well done, bravo",
    "kya scene":        "what's the situation",
    "scene on hai":     "something exciting is happening",
    "full too much":    "over the top, excessive",
    "too much yaar":    "you're too much, friend",
    "mind it":          "watch out, be careful",
    "no tension":       "don't worry",
    "tension nahi":     "no stress, don't worry",
    "mast hai":         "it's great",
    "ekdum":            "completely, absolutely",
    "jhakaas":          "excellent, awesome (Marathi/Hindi)",
    "bindaas chal":     "go carefree, relax",
    "kya bolti public": "what do you say, everyone",
    "public":           "people, everyone (desi slang)",
    # ── More gaming / streaming ───────────────────────────────────────────
    "ggez":             "good game, easy win",
    "inting":           "intentionally feeding or throwing a game",
    "int":              "intentionally throwing a game",
    "griefing":         "deliberately ruining others' fun in a game",
    "griefer":          "someone who ruins others' fun in a game",
    "smurf":            "a skilled player using a low-level account",
    "smurfing":         "using a low-level account to dominate",
    "boosted":          "carried to a rank you don't deserve",
    "hardstuck":        "unable to rank up past a certain level",
    "one trick":        "someone who only plays one character",
    "main":             "primary character or role",
    "off meta":         "not using the current best strategy",
    "on meta":          "using the current best strategy",
    "patch":            "a game update",
    "nerfed":           "weakened by a game update",
    "buffed":           "strengthened by a game update",
    "clipped that":     "captured a great gaming moment",
    "clip it":          "record that moment",
    "pog":              "exciting or hype moment",
    "poggers":          "very exciting or hype",
    "pogchamp":         "an exciting or impressive moment",
    "copium":           "false hope or denial",
    "hopium":           "optimistic hope despite odds",
    "malding":          "mad and balding from frustration",
    "pepega":           "doing something foolish (streaming meme)",
    "sadge":            "sad (streaming meme)",
    "kekw":             "laughing hard (streaming meme)",
    "monkas":           "nervous or anxious (streaming meme)",
    "based department": "calling someone admirably authentic",
    "skill issue":      "you lack the skill (often joking insult)",
    "git gud":          "get good, improve your skill",
    "touch grass gamer": "go outside instead of gaming",
    "sweaty":           "trying too hard in a game",
    "sweaty tryhard":   "someone who tries excessively hard",
    "casual":           "playing for fun, not competitively",
    "ranked":           "competitive mode in a game",
    "unranked":         "non-competitive mode",
    "gg wp":            "good game, well played",
    "wp":               "well played",
    "gl hf":            "good luck, have fun",
    "dc":               "disconnected from the game",
    "dc'd":             "disconnected from the game",
    "lag spike":        "sudden internet delay",
    "ping":             "network delay in a game",
    "high ping":        "bad network delay",
    "low ping":         "good network connection",
    "cracked":          "extremely skilled at a game",
    "cracked at":       "extremely skilled at something",
    "goated at":        "the greatest at something",
    "built different":  "naturally superior or unique",
    "different breed":  "on another level entirely",
    "goated with the sauce": "the greatest with style and skill",
}

# ---------------------------------------------------------------------------
# Plain English → Gen-Z
# ---------------------------------------------------------------------------
PLAIN_TO_GENZ: dict[str, str] = {
    "honestly":                     "no cap",
    "no lie":                       "no cap",
    "really good":                  "bussin",
    "very good":                    "bussin fr",
    "great job":                    "you ate that",
    "well done":                    "slay",
    "amazing work":                 "you slayed",
    "okay sure":                    "bet",
    "sounds good":                  "bet",
    "I agree":                      "bet",
    "for real":                     "fr",
    "seriously":                    "deadass",
    "suspicious":                   "kinda sus",
    "mediocre":                     "mid",
    "average":                      "mid",
    "charisma":                     "rizz",
    "charming":                     "got rizz",
    "embarrassing":                 "so cringe",
    "gossip":                       "tea",
    "share the gossip":             "spill the tea",
    "going to":                     "finna",
    "very exciting":                "so lit",
    "stylish":                      "drip",
    "looking great":                "snatched",
    "I can't stop thinking about it": "it's living rent free in my head",
    "delusional":                   "delulu",
    "a win":                        "W",
    "a loss":                       "L",
    "greatest of all time":         "goated",
    "best friend":                  "bestie",
    "not going to lie":             "ngl",
    "to be honest":                 "tbh",
    "I swear":                      "on god",
    "understandable":               "valid",
    "memorable":                    "iconic",
    "go outside":                   "touch grass",
    "show off":                     "flex",
    "upset":                        "salty",
    "bothered":                     "pressed",
    "mood":                         "vibe",
    "atmosphere":                   "vibe",
    "if you understand you understand": "iykyk",
    "did perfectly":                "understood the assignment",
    "confidence":                   "main character energy",
    "in trouble":                   "cooked",
    "ruined":                       "cooked",
    "overpraise":                   "glaze",
    "focused":                      "locked in",
    "perfect":                      "ate",
    "weird":                        "giving ohio",
    "excellent":                    "fire",
    "very cool":                    "lowkey fire",
    "not cool":                     "mid ngl",
    "I don't know":                 "idk",
    "laughing":                     "lmao",
    "very funny":                   "sending me",
    "I'm laughing":                 "I'm dead",
    "that's funny":                 "that's sending me",
    "I'm bored":                    "this is so mid",
    "I'm excited":                  "I'm so hyped rn",
    "I'm tired":                    "I'm cooked",
    "I'm happy":                    "I'm vibing",
    "I'm sad":                      "I'm not okay ngl",
    "I'm angry":                    "I'm pressed rn",
    "I'm confused":                 "I'm so lost rn",
    "I'm surprised":                "no way fr",
    "I'm proud":                    "I ate that ngl",
    "I'm nervous":                  "I'm lowkey stressed",
    "I'm scared":                   "I'm lowkey shaking",
    "I'm disappointed":             "that's an L",
    "I'm impressed":                "sheesh",
    "I'm grateful":                 "I'm so grateful fr",
    "I'm sorry":                    "my bad fr",
    "thank you":                    "ty bestie",
    "you're welcome":               "no cap anytime",
    "please":                       "pls bestie",
    "stop":                         "chill",
    "go away":                      "touch grass",
    "I love it":                    "I'm obsessed no cap",
    "I hate it":                    "it's giving ick",
    "that's bad":                   "that's an L fr",
    "that's good":                  "that's a W",
    "that's amazing":               "that's bussin no cap",
    "that's boring":                "that's so mid",
    "that's weird":                 "that's giving ohio",
    "that's suspicious":            "that's sus fr",
    "that's embarrassing":          "that's so cringe",
    "that's impressive":            "sheesh no cap",
    "that's funny":                 "I'm dead fr",
    "that's sad":                   "that's an L ngl",
    "that's unfair":                "that's not valid",
    "that's fair":                  "that's valid",
    "that's obvious":               "it's giving obvious",
    "that's unexpected":            "no way fr",
    "that's perfect":               "that ate no cap",
    "that's terrible":              "that's cooked fr",
    "that's great":                 "that slaps no cap",
    "that's okay":                  "it's valid",
    "that's not okay":              "that's not it bestie",
    "do your best":                 "slay bestie",
    "good luck":                    "go off bestie",
    "be careful":                   "don't be sus",
    "calm down":                    "chill fr",
    "hurry up":                     "no cap move faster",
    "slow down":                    "lowkey chill",
    "pay attention":                "lock in fr",
    "agreed":                       "clock it",
    "exactly":                      "clock it",
    "that's true":                  "clock it",
    "you're right":                 "clock it",
    "that's exactly right":         "clock that",
    "spotted it":                   "clocked it",
    "called it out":                "clocked it",
    "work hard":                    "grind fr",
    "take a break":                 "touch grass fr",
    "be honest":                    "no cap fr",
    "be quiet":                     "say less",
    "I understand":                 "understood the assignment",
    "I don't understand":           "I'm so lost rn",
    "I agree":                      "bet fr",
    "I know right":                 "ikr",
    "I know, right":                "ikr",
    "I disagree":                   "that's not it",
    "I'm not sure":                 "lowkey idk",
    "I think so":                   "lowkey yeah",
    "I don't think so":             "lowkey no",
    "maybe":                        "lowkey maybe",
    "definitely":                   "no cap fr",
    "never":                        "not in this lifetime fr",
    "always":                       "literally always no cap",
    "sometimes":                    "lowkey sometimes",
    "often":                        "highkey often",
    "rarely":                       "lowkey rarely",
    # UK / regional reverse mappings
    "what's going on":              "wagwan",
    "what's up":                    "wsg",
    "alright":                      "safe",
    "very attractive":              "peng ting",
    "attractive":                   "leng",
    "ugly":                         "butters",
    "exhausted":                    "knackered",
    "very disappointed":            "gutted",
    "very pleased":                 "chuffed",
    "seems suspicious":             "dodgy",
    "a lot of":                     "bare",
    "very":                         "proper",
    "friend":                       "mate",
    "bro":                          "bruv",
    "annoying":                     "long",
    "unfortunate":                  "peak",
    "acting crazy":                 "moving mad",
    "obvious":                      "bait",
    "broke":                        "skint",
    "really excellent":             "mint",
    "fun":                          "craic",
    "fine":                         "grand",
    "small":                        "wee",
    "freezing":                     "baltic",
    "disgusting":                   "minging",
    "lovely":                       "lush",
    "shocked":                      "gobsmacked",
    "well done":                    "shabaash",
    "stop it":                      "bas kar",
    "don't worry":                  "no tension",
    "desperate":                    "down bad",
    "no way":                       "no shot",
    "mutual followers":             "moots",
    "private account":                "finsta",
    "affordable alternative":       "dupe",
    "desperate for someone":        "down horrendous",
    "understated luxury":           "quiet luxury",
    "we are back":                  "we're so back",
    "it's over":                    "it's so joever",
    "be serious":                   "be fr",
    "go outside for once":          "touch some grass",
    "got the reference":            "understood the reference",
    "got the backstory":            "understood the lore",
    "very skilled":                 "cracked",
    "on another level":             "different breed",
    "trying too hard":              "sweaty",
    "good game":                    "gg",
    "well played":                  "wp",
    "exciting moment":              "poggers",
    "false hope":                   "copium",
    "you need skill":               "skill issue",
    # Abbreviation reverse mappings
    "on my way":                    "omw",
    "what are you doing":           "wyd",
    "where are you":                "wya",
    "how are you doing":            "hyd",
    "how are you":                  "hru",
    "let me know":                  "lmk",
    "don't worry":                  "dw",
    "my bad":                       "mb",
    "sorry":                        "sry",
    "I guess":                      "ig",
    "I don't care":                 "idc",
    "I don't think":                "idt",
    "I don't think so":             "idts",
    "on the phone":                 "otp",
    "in case you missed it":        "icymi",
    "too much information":         "tmi",
    "of course":                    "ofc",
    "I love you":                   "ily",
    "I love you too":               "ily2",
    "I love you so much":           "ilysm",
    "thank you very much":          "tyvm",
    "see you later":                "cul",
    "talk to you soon":             "ttys",
    "good night":                   "gn",
    "good morning":                   "gm",
    "good luck":                    "gl",
    "have fun":                     "hf",
    "happy birthday":               "hbd",
    "nothing much":                 "nm",
    "whatever":                     "w/e",
    "before":                       "b4",
    "about":                        "abt",
    "though":                       "tho",
    "through":                      "thru",
    "with":                         "w/",
    "without":                      "w/o",
    "seriously":                    "srsly",
    "probably":                     "prob",
    "for sure":                     "defo",
    "public service announcement":  "psa",
    "do not interact":              "dni",
    "not safe for work":            "nsfw",
    "sorry for your loss":          "sfyl",
    "for real for real":            "frfr",
    "kind of":                      "kinda",
    "sort of":                      "sorta",
    "want to":                      "wanna",
    "got to":                       "gotta",
    "let me":                       "lemme",
    "give me":                      "gimme",
    "trying to":                    "tryna",
    "about to":                     "bouta",
    "seriously though":             "srsly tho",
    "you all":                      "yall",
    "don't know":                   "dunno",
}

SLANG_MODES = {
    "genz_to_plain": {
        "id":           "genz_to_plain",
        "label":        "Gen Z → Plain English",
        "desc":         "Decode slang so parents and older generations understand",
        "source_label": "What they said (Gen Z)",
        "target_label": "Plain English",
    },
    "plain_to_genz": {
        "id":           "plain_to_genz",
        "label":        "Plain English → Gen Z",
        "desc":         "Rephrase so younger generations relate",
        "source_label": "What you mean (Plain)",
        "target_label": "Gen Z friendly",
    },
}


def get_slang_modes() -> list[dict]:
    return list(SLANG_MODES.values())


def get_glossary(limit: int = 60) -> list[dict]:
    items = [
        {"slang": k, "meaning": v}
        for k, v in sorted(GENZ_TO_PLAIN.items(), key=lambda x: len(x[0]), reverse=True)
    ]
    return items[:limit]


def _apply_dictionary(text: str, mapping: dict[str, str]) -> tuple[str, list[dict]]:
    """
    Replace slang terms in `text` using `mapping`.
    - Longest terms matched first (prevents partial replacements)
    - Whole-word boundary matching for single words
    - Case-insensitive
    - Tracks matched terms for the UI
    - Avoids double-replacing already-replaced spans
    """
    result = text
    matched: list[dict] = []
    seen_slangs: set[str] = set()

    # Sort by length descending so multi-word phrases match before single words
    sorted_terms = sorted(mapping.keys(), key=len, reverse=True)

    for term in sorted_terms:
        if term.lower() in seen_slangs:
            continue

        # Use word boundaries for single-word terms, plain match for phrases
        if " " in term:
            pattern = re.compile(re.escape(term), re.IGNORECASE)
        else:
            pattern = re.compile(r"\b" + re.escape(term) + r"\b", re.IGNORECASE)

        if pattern.search(result):
            seen_slangs.add(term.lower())
            matched.append({"slang": term, "meaning": mapping[term]})
            result = pattern.sub(mapping[term], result)

    # Clean up: collapse multiple spaces, fix spacing around punctuation
    result = re.sub(r" {2,}", " ", result)
    result = re.sub(r" ([,.!?;:])", r"\1", result)

    return result, matched


def translate_slang(text: str, mode: str = "genz_to_plain", use_ai: bool = True) -> dict:
    if not text or not text.strip():
        return {
            "translated_text": "",
            "matched_terms": [],
            "mode": mode,
            "confidence": 0.0,
            "used_ai": False,
        }

    if mode == "genz_to_plain":
        mapping = GENZ_TO_PLAIN
    elif mode == "plain_to_genz":
        mapping = PLAIN_TO_GENZ
    else:
        raise ValueError(f"Unknown slang mode: {mode}")

    result, matched = _apply_dictionary(text, mapping)
    used_ai = False

    unchanged = result.strip().lower() == text.strip().lower()
    word_count = len(text.split())

    # Polish with AI when terms matched, phrase is long enough, or dictionary left slang unchanged
    if use_ai and (len(matched) > 0 or word_count >= 2 or (unchanged and word_count >= 1)):
        ai_result = polish_slang_with_ai(text, result, mode)
        if ai_result.get("used_ai"):
            result = ai_result["polished_text"]
            used_ai = True

    # Confidence: base 0.70, +0.04 per matched term, +0.10 if AI polished
    confidence = min(0.98, 0.70 + len(matched) * 0.04 + (0.10 if used_ai else 0))

    return {
        "translated_text": result.strip(),
        "original_text": text,
        "matched_terms": matched,
        "mode": mode,
        "confidence": round(confidence, 2),
        "used_ai": used_ai,
    }
